language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_860836177ab6_key -iv $encrypted_860836177ab6_iv
  -in team/src/main/resources/application.properties.enc -out team/src/main/resources/application.properties -d
